language: generic
dist: trusty
services:
  - docker

addons:
  apt:
    update: true

branches:
  only:
    - master
    - develop

before_script:
  #PACKAGES NEEDED FOR SSH CONNECTION
  - sudo apt-get install sshpass
  # DISABLE HOST CHECKING IN SSH CONNECTION
  - echo "StrictHostKeyChecking no" >> ~/.ssh/config

after_success:
  - docker build -t jcalarcon/face-recognition ./ia-face-expression
  docker build -t jcalarcon/nginx-face-recognition ./nginx
  #LOGIN to DOCKER CLI.
  - echo  "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #PUSH THESE IMAGES TO DOCKERHUB
  - docker push jcalarcon/face-recognition
  - docker push jcalarcon/nginx-face-recognition

#DEPLY TO VPS
deploy:
  skip_cleanup: true
  provider: script
  script: sshpass -p "$VPS_PASSWORD" ssh "$VPS_USER"@"$VPS_IP" "cd $VPS_DOCKER_PATH && docker-compose down && docker image rm jcalarcon/jenika-frontend && docker-compose up --build -d"
  on:
    branch: master
